import type { EvidenciaCasoTeste } from "./tipos";

export const CASOS_TESTE: EvidenciaCasoTeste[] = [
  {
    id: "TC-01",
    titulo: "Wallet baseline",
    descricao: "Análise inicial de uma wallet sem atividade relevante.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-02",
    titulo: "Atividade normal",
    descricao: "Wallet com múltiplas interações normais.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-03",
    titulo: "Treasury inativa",
    descricao: "Analisar W3 sem enviar transação para preservar o perfil de baixa atividade.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-04",
    titulo: "Interação com contrato",
    descricao: "Wallet interage com o contrato controlado.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-05",
    titulo: "Interação suspeita",
    descricao: "Execução do marcador de interação suspeita.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-06",
    titulo: "Aprovação controlada",
    descricao: "Criação de uma aprovação controlada no contrato de teste.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-07",
    titulo: "Revogação da aprovação",
    descricao: "Remoção da aprovação criada no caso anterior.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-08",
    titulo: "Before / After",
    descricao: "Comparação da resposta da NZOChain antes e depois da interação.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-09",
    titulo: "Comparação entre wallets",
    descricao: "Comparação de duas wallets após interações semelhantes.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  },
  {
    id: "TC-10",
    titulo: "Fluxo end-to-end",
    descricao: "Connect → autenticação → análise → ação → nova análise → evidência.",
    wallet: null,
    network: null,
    contract: null,
    estado: "pendente",
    before: null,
    action: null,
    after: null,
    observacao: "",
    createdAt: "",
    updatedAt: ""
  }
];
